[package]
name = "multiping"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
console = "0.16.0"
ping = "0.6.1"
rand = "0.9.1"

# Shut some warnings up while I'm starting off
# TODO: remove these
[lints.rust]
unused = "allow"
